#!/bin/bash

#Bugs to fix
#LLIU**************************************
# argument parsing??

# should print $ sign instead of nothing
echo "$"
echo $

#***************************************



#bash: export: `A-': not a valid identifier
# Fix export
export A-
export =
export HELLO-=123
export 123
export 123=KEY

# in case of syntax error, return but not exit


# OTHERS
<<LMT 'grep test' "-l" |wc -l > outfile
# if the content of the file is test1\n test2\n, ours write 2 into outfile, while bash write 1


# exit 100 is not exiting
# exit +100 show as syntax error

#HEREDOC: signal part


#EXITSTATUS
